### ISSUE TITLE
Bibliography: year preference when there is more than one

### ISSUE THREAD

**Issue by chbrown** [semprag/semprag.github.com#6]
I've encountered a couple cases where the electronic / "first available online" date is a different year than the more official / printed / "cite this as" year.

Should we prefer one of these over the other? I see three choices:

1. Prefer the more official / printed year
2. Prefer the minimum year (not always the "first available online" date!)
3. Let the author pick (no preference)

Examples:
* http://dx.doi.org/10.1093/jos/ffs001
* http://dx.doi.org/10.1007/s10988-011-9103-8
* http://dx.doi.org/10.1007/s10988-008-9023-4

**Comment by fintelkai** [comment]
The official printed year.

**Comment by chbrown** [comment]
Leaving open until I add this to the documentation...
